language: python
sudo: false

python:
- 2.7

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TOXENV=ui-tests
addons:
  firefox: latest
before_install:
  - wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - firefox --version
  - geckodriver --version
install:
  - npm install
  - pip install tox-travis
before_script:
  - npm start &
  - sh -e /etc/init.d/xvfb start
  - sleep 10
script:
  - tox
